// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFAKGcerm0Onf5Xa9i6gyabs0N1JCuuq8',
    appId: '1:712388228451:web:280a661ce91876fb850f56',
    messagingSenderId: '712388228451',
    projectId: 'fithub-89059',
    authDomain: 'fithub-89059.firebaseapp.com',
    storageBucket: 'fithub-89059.appspot.com',
    measurementId: 'G-NV0JP29S6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7ZTxWwQYbin5kIE62fFf0f2jV3InT2ZU',
    appId: '1:712388228451:android:da6c6b2497c95ec3850f56',
    messagingSenderId: '712388228451',
    projectId: 'fithub-89059',
    storageBucket: 'fithub-89059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdVTUUkWpF4hN57MkbnojjoOhe_WQwDQo',
    appId: '1:712388228451:ios:0651bad26832d780850f56',
    messagingSenderId: '712388228451',
    projectId: 'fithub-89059',
    storageBucket: 'fithub-89059.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdVTUUkWpF4hN57MkbnojjoOhe_WQwDQo',
    appId: '1:712388228451:ios:0651bad26832d780850f56',
    messagingSenderId: '712388228451',
    projectId: 'fithub-89059',
    storageBucket: 'fithub-89059.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFAKGcerm0Onf5Xa9i6gyabs0N1JCuuq8',
    appId: '1:712388228451:web:5b594182d5f8d787850f56',
    messagingSenderId: '712388228451',
    projectId: 'fithub-89059',
    authDomain: 'fithub-89059.firebaseapp.com',
    storageBucket: 'fithub-89059.appspot.com',
    measurementId: 'G-4TDXWFWEHD',
  );
}
